### ISSUE TITLE
Join wrong room upon enter

### ISSUE THREAD

**Issue by arangace** [arangace/CreamCat#50]
**Describe the bug**
Joins the wrong room when trying to join the room for the first time

**To Reproduce**
1. Go to 'localhost:3000/Joinroom'
2. Click on 'join room'
3. Enter room ID

**Expected behavior**
Joins the correct room upon ID entered

**Screenshots**

**Desktop (please complete the following information):**

**Comment by nivekyee** [comment]
Solved #49
